sudo: false
language: node_js
node_js:
- 6
script:
- npm run travis
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && codeclimate-test-reporter < ./coverage/lcov.info || true'
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && ./scripts/checkPullRequest.js'
notifications:
  slack:
    secure: MPEurDUvYfcl3b5Hji/42sKF6TQLRcrkqMfKINy6buFePKdbkwDjQd+r0GYAC153lLpbJeiFy7p8TAVp2QP3wmC02ea9n3CG8juKpCBabyaZq3RBvhJ7kKUd/BdTLPNWU1ttSrQlzOoAs3HcuEAaeUzhW3d0LPH+bVvYx4aG8UM=
env:
  global:
  - secure: dczgNmycwYw9E7aAQN+/Ad/l93SIWTPDCnJ39eLWb0Wwp4CdvNAfdt9EV9ysQSba5ylaD7I1dD6nmFkZla1m8UtxdrPbTm/gf0v40ZXgSErxkFpRt+cj442j6v/IqFi9Ok78KwVpeyUjraWD5HToCwBI9BxtpoqrCVh84DfplSo=
  - secure: aEeBtPvQ8G9448/lwKuJRVEbhCczPcgc090iiHxoVZAX41n2PxzSd8qId/3J3ctU416STfxqVieR9E8+Tj8rG1KyFCN6YTh92ll89IGAK1pl+kmKxkUqYZnYRfCax6IDTvnjzDF0v3xdQdgMiJ/1lbdwZ/WjqJrx1PFi1qRkB50=
