sudo: false
language: node_js
node_js:
- 6.1.0
script:
- npm run travis
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && codeclimate-test-reporter < ./coverage/lcov.info
  || true'
notifications:
  slack:
    secure: MPEurDUvYfcl3b5Hji/42sKF6TQLRcrkqMfKINy6buFePKdbkwDjQd+r0GYAC153lLpbJeiFy7p8TAVp2QP3wmC02ea9n3CG8juKpCBabyaZq3RBvhJ7kKUd/BdTLPNWU1ttSrQlzOoAs3HcuEAaeUzhW3d0LPH+bVvYx4aG8UM=
env:
  global:
  - GH_REF: github.com/dhis2/d2.git
  - secure: dczgNmycwYw9E7aAQN+/Ad/l93SIWTPDCnJ39eLWb0Wwp4CdvNAfdt9EV9ysQSba5ylaD7I1dD6nmFkZla1m8UtxdrPbTm/gf0v40ZXgSErxkFpRt+cj442j6v/IqFi9Ok78KwVpeyUjraWD5HToCwBI9BxtpoqrCVh84DfplSo=
  - secure: d0W371ABiCdbN0RJHm8HfDnzd8P/TTRxOj770+1xcZNW67EAHQsJL6L8mT8H6T3nCP/PhW2+r2jr/OWiukIknQ6bK+DXzZMHI45klzRtoyLjkZl8qiwvxsx6maSd5/koy8zKhgltGW7gtb8jec68ZUNUrrnKxyaLWiqEb6OUn/8=
before_deploy:
  - git config user.name "Travis CI"
  - git config user.email "mark@dhis2.org"
  - npm version patch && npm run build
  - git log -10 --oneline
deploy:
  provider: npm
  email: mark@dhis2.org
  api_key:
    secure: VPyATOy4THntMa7rhUqsL5aAGZfEyiHBETBDIbUQjIrGp447P+olpAOWUNZuKjjQhnKQg0OODiV+51+MY9EQBEa8w6crpiQR+m0NTxj/gMkVMXxfIqH1LaLbFYfH+85mF4Ik4cK5VfOlxTdRY89jDm7vGJavnQhLg9auT7sFWKM=
  on:
    branch: v25
  skip_cleanup: true
after_deploy:
  - git log -10 --oneline
  - git push https://${GITHUB_TOKEN}@${GH_REF} HEAD:v25 --quiet
  - git push https://${GITHUB_TOKEN}@${GH_REF} --tags --quiet
