language: node_js
node_js:
- '0.10'
before_install:
- npm install -g jspm@0.16.0-beta
- jspm config registries.github.auth $JSPM_GITHUB_TOKEN
- jspm install
- jspm install --dev
script:
- gulp ci:travis
- cd src
- cat ../coverage/lcov.info | ../node_modules/coveralls/bin/coveralls.js
env:
  global:
  - secure: Y+1gxlnruQWWAUALz2ybg8eGE47ND9qH9weFzHnoxaNjVVuuu5ObAIi74GZIST9t/i94pNA8bkmn9yYeQkfcyOXHo5jDyBnRlAnzQUgBTY1DcVD5JmN1pjpQMRE+vz1h3ChFPu6l/4RpmtlfbdBcfVC3aGARrvDui2/rES368aY=
