language: node_js

node_js:
  - "0.10"

before_script:
  - bower install

script:
  - gulp travis
  - cd src
  - cat ../coverage/phantomjs/lcov.info | ../node_modules/coveralls/bin/coveralls.js
  - rm -rf ../coverage
